### PR TITLE
Quit button added to GUI

### PR DESCRIPTION
**Pull request by farooqkz**
well, it was useful for me :)

### CODE REVIEW

**Comment by farooqkz** [comment]
othman_after
othman_before
Note: It is written in Sahih Bukhari that anyone who reads(or recites?) those two last ayat in night, they will be enough for him.

**Comment by muayyad-alsadi** [comment]
But the window manager provide quit button as in our screenshot in the readme

**Comment by muayyad-alsadi** [comment]
https://github.com/flathub/com.github.ojubaorg.Othman/blob/master/othman-screenshot.png

**Comment by farooqkz** [comment]
1. Not all WMs provide a "quit button"
2. I think the program should have a quit button or such a thing which does not depend on WM.

**Comment by muayyad-alsadi** [comment]
I'm very sorry, we are not reinventing the square wheels

look at your favourite apps: calculator, calendar, gedit, ...etc.

We might move to client side decoration, patches are welcome for that, I'll close this one for now

**Comment by farooqkz** [comment]
@muayyad-alsadi, I don't understand.

**Comment by farooqkz** [comment]
If that's Quit button of WM, the problem still exist.
P.S.: What are those softwares in the picture?

**Comment by muayyad-alsadi** [comment]
the title bar with buttons including quit is done by application not WM.

the screenshot is for [thawab-lite](https://github.com/ojuba-org/thawab-lite)

**Pull request closed without merging**
